// design-sync bundle entry — re-exports the scoped XN design-system surface.
// Hand-authored (not generated): keeps the bundle to the 18 scoped components
// plus their sub-parts, instead of synthesizing over all of src/.
export * from '@/components/ui/button'
export * from '@/components/ui/badge'
export * from '@/components/ui/card'
export * from '@/components/ui/input'
export * from '@/components/ui/dialog'
export * from '@/components/ui/alert-dialog'
export * from '@/components/ui/dropdown-menu'
export * from '@/components/ui/popover'
export * from '@/components/ui/separator'
export * from '@/components/ui/sheet'
export * from '@/components/ui/skeleton'
export * from '@/components/ui/switch'
export * from '@/components/ui/table'
export * from '@/components/ui/tabs'
export * from '@/components/ui/tooltip'
export { Toast } from '@/components/ui/toast'
export { default as TypeBadge } from '@/components/TypeBadge'
export { default as StatusBadge } from '@/components/StatusBadge'
